version: '3'

services:
  web:
    build: .
    container_name: datachat
    ports:
      - "8501:8501"
    working_dir: /app
    command: streamlit run app/app.py
    volumes:
      #- ./app:/app
      - ${CONFIG}:/config
      - ${DATADIR}:/data
      - ${CACHEDIR}:/root/.cache
      - ${INSTALLATION}:/app/installation
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_ENABLECORS=false
      - OLLAMA
      - MODEL
      - INTRO
      - TITLE
      - FAKEDNS
      - DATADIR
      - IDATADIR
      - SOURCES
    restart: always

